apiVersion: v1
kind: Secret
metadata:
    name: chatapp-secrets
    namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    jwt: {{ .Values.secrets.jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secrets
    namespace: {{ .Values.namespace }}
type: Opaque
stringData:
    username: {{ .Values.mongodb.auth.username | quote }}
    password: {{ .Values.mongodb.auth.password | quote }}