apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chatapp-secrets
  namespace: chat-app
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: chatapp-secrets
    creationPolicy: Owner
  data:
    - secretKey: jwt
      remoteRef:
        key: chatapp/jwt-secret