apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secrets
  namespace: chat-app
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mongodb-secrets
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: chatapp/mongodb-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: chatapp/mongodb-credentials
        property: password