#The Triggers
name: Terraform Security Scan

on:
  push:
    branches: [main]
    paths:
      - "terraform/**"
  pull_request:
    paths:
      - "terraform/**"


#Execution Environment

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     
      - name: Scan Terraform for misconfigurations
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: terraform/
          format: table
          severity: CRITICAL,HIGH
          exit-code: "1"
